import { NextResponse } from "next/server";
import { rateLimit, clientIp } from "@/lib/rateLimit";
import { evaluateTrajectory, type EvalResult, type ToolCall } from "@/lib/trajectory-eval";
import { evaluateViaGovernance } from "@/lib/governance-client";
import { extractTrajectory, heuristicPlan } from "@/lib/planner";
import { runHuggingFacePlanner, hfPlannerConfigured, PLANNER_MODEL } from "@/lib/hf-planner";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type GovSource = "morrison" | "heuristic";
type PlannerSource = "huggingface" | "heuristic";

interface Ok extends EvalResult {
  ok: true;
  source: GovSource; // governance verdict provenance (morrison = live engine)
  task: string;
  trajectory: ToolCall[];
  planner: { source: PlannerSource; model: string; note: string };
}
type Resp = Ok | { ok: false; error: string };

/**
 * Generate a tool trajectory from a plain-English task using the SAME Hugging
 * Face planner flow as the smoke test, then evaluate it through the REAL
 * governance engine. The planner only PROPOSES; the verdict is always the live
 * engine's (never hardcoded). Nothing is ever executed.
 */
export async function POST(req: Request): Promise<NextResponse<Resp>> {
  const rl = rateLimit(clientIp(req.headers), { bucket: "plan", max: 12 });
  if (!rl.ok) {
    return NextResponse.json(
      { ok: false, error: "Too many requests. Please try again shortly." },
      { status: 429, headers: { "Retry-After": String(Math.ceil(rl.retryAfterMs / 1000)) } },
    );
  }

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ ok: false, error: "Malformed JSON." }, { status: 400 });
  }

  const task = String((body as { task?: unknown })?.task ?? "").trim();
  if (task.length < 3) {
    return NextResponse.json({ ok: false, error: "Describe a task in a few words (min 3 characters)." }, { status: 422 });
  }
  if (task.length > 500) {
    return NextResponse.json({ ok: false, error: "Task is too long (max 500 characters)." }, { status: 422 });
  }

  // ── 1. Plan — Hugging Face planner first, transparent heuristic fallback ──
  let trajectory: ToolCall[] | null = null;
  let plannerSource: PlannerSource = "heuristic";
  let plannerNote = "";

  if (hfPlannerConfigured()) {
    try {
      // One stricter retry, mirroring the notebook's duplicate-key handling.
      for (let attempt = 0; attempt < 2 && !trajectory; attempt++) {
        const nudge = attempt === 0 ? "" : "\n\nReturn ONE JSON object with EXACTLY ONE 'trajectory' key. No duplicate keys, no prose.";
        const raw = await runHuggingFacePlanner(task + nudge);
        const parsed = extractTrajectory(raw);
        if (parsed.trajectory) {
          trajectory = parsed.trajectory;
          plannerSource = "huggingface";
          plannerNote = parsed.reason;
        } else {
          plannerNote = parsed.reason;
        }
      }
    } catch (err) {
      plannerNote = `Hugging Face planner unavailable (${(err as Error).message}); used keyword fallback.`;
    }
  } else {
    plannerNote = "Hugging Face planner not configured on this deployment; used keyword fallback.";
  }

  if (!trajectory) {
    trajectory = heuristicPlan(task);
    plannerSource = "heuristic";
    if (!plannerNote) plannerNote = "Generated by the keyword fallback planner.";
  }

  // ── 2. Evaluate — REAL engine; heuristic only if the engine is unreachable ──
  let result: EvalResult;
  let source: GovSource = "heuristic";
  try {
    result = await evaluateViaGovernance(trajectory);
    source = "morrison";
  } catch (err) {
    console.warn("[plan-and-evaluate] governance unavailable, heuristic fallback:", (err as Error).message);
    result = evaluateTrajectory(trajectory);
  }

  const res = NextResponse.json<Resp>({
    ok: true,
    source,
    task,
    trajectory,
    planner: { source: plannerSource, model: plannerSource === "huggingface" ? PLANNER_MODEL : "keyword-fallback", note: plannerNote },
    ...result,
  });
  res.headers.set("x-governance-source", source);
  res.headers.set("x-planner-source", plannerSource);
  return res;
}
